model:
    depth: 12
    mlp_ratio: 2.0
    cross_layers: [3, 7, 11, 15, 19, 23]
    num_heads: 8
    add_inject: false

data:
    num_classes: -1
    octree_root_num: 64
    unit_length_list: [361, 139, 139]

diffusion:
    noise_schedule: "xg_linear"
    diffusion_steps: 1000

vae:
    latent_ratio: 4
    layer_num: 8
